### ISSUE TITLE
Create a simple website

### ISSUE THREAD

**Issue by dmil** [escherer538/simple-website#1]

**Comment by escherer538** [comment]
https://github.com/escherer538/simple-website/commit/9206ee3a658b9a480cc5067e367e3ebd3542a9dc here's a commit, created the website

**Comment by dmil** [comment]
I don't see the website

**Comment by escherer538** [comment]
looks online to me https://escherer538.github.io/simple-website/

**Comment by dmil** [comment]
looks goooood
